In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs

In [2]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

## Non Preferred Approach

In [3]:
model = Sequential([
    Dense(25, activation='relu'),
    Dense(15, activation='relu'),
    Dense(4, activation='softmax')
])

model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
             optimizer=tf.keras.optimizers.Adam(0.001))

model.fit(X_train, y_train, epochs=10)

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 0.8653
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.4290
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1880
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1090
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0805
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0664
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0581
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0527
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0488
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0454


In [4]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred[:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 798us/step
[[9.5949048e-04 7.3370046e-04 9.7942632e-01 1.8880546e-02]
 [9.9313873e-01 6.5130158e-03 3.1893779e-04 2.9220480e-05]]
largest value 0.99999976 smallest value 3.226654e-11


## Preferred Approach

In [5]:
preferred_model = Sequential([
    Dense(25, activation='relu'),
    Dense(15, activation='relu'),
    Dense(4, activation='linear')
])

preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), #<---- Note
    optimizer=tf.keras.optimizers.Adam(0.001))

preferred_model.fit(X_train, y_train, epochs=10)

Epoch 1/10
63/63 [==============================] - 0s 2ms/step - loss: 0.9342
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.4797
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.3033
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1734
Epoch 5/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1024
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0709
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0561
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0476
Epoch 9/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0424
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0386


In the preffered model outputs are not probabilites, but can range from large negative numbers to large positive numbers. The output must be sent through a softmax when performing a prediction that expects a probability. 

In [6]:
p_preferred = preferred_model.predict(X_train)
print(f'two example output vectors:\n {p_preferred[:2]}')
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 [==============================] - 0s 745us/step
two example output vectors:
 [[-2.3929222  -1.4135342   2.8695393  -0.96014667]
 [ 3.9552495  -0.9764768  -7.089743   -8.105098  ]]
largest value 11.597968 smallest value -11.299906


In [7]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f'two example output vectors:\n {sm_preferred[:2]}')
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[4.9798554e-03 1.3260491e-02 9.6089238e-01 2.0867158e-02]
 [9.9281621e-01 7.1622138e-03 1.5852202e-05 5.7428365e-06]]
largest value 0.99999976 smallest value 2.3358587e-10


To select the most likely category, the softmax is not required. One can find the index of the largest output using np.argmax().

In [8]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-2.3929222  -1.4135342   2.8695393  -0.96014667], category: 2
[ 3.9552495 -0.9764768 -7.089743  -8.105098 ], category: 0
[ 2.5206802  -0.44733834 -5.4199004  -6.5428867 ], category: 0
[-2.7617996  2.8754823 -3.2151022 -3.6707163], category: 1
[-1.708238  -1.8597742  3.8138444 -2.8284914], category: 2
